$primary = {{colors.primary.hex_stripped}}
$red = {{colors.terminal.normal.red.hex_stripped}}
$yellow = {{colors.terminal.normal.yellow.hex_stripped}}
$white = {{colors.terminal.normal.white.hex_stripped}}
