[ids]

*

[main]
 
# disable numblo
numlock = noop

# Map caps to super when held, esc when pressed for 150 ms
# capslock = overload(meta, esc)
capslock = overloadt2(meta, esc, 150)

# map control right click to middle mouse click
[control]
mouse2 = middlemouse
