#!/bin/bash

# https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

scheme="$1"
if [[ ! -f "$scheme" ]]; then
    scheme="$SCRIPT_DIR/colorschemes/$(ls -p $SCRIPT_DIR/colorschemes | grep -v / | fzf)"
fi

echo "$scheme"

if [[ -f "$scheme" ]]; then
    matugen json "$scheme"
fi
