color0 {{colors.terminal.normal.black.hex}}
color1 {{colors.terminal.normal.red.hex}}
color2 {{colors.terminal.normal.green.hex}}
color3 {{colors.terminal.normal.yellow.hex}}
color4 {{colors.terminal.normal.blue.hex}}
color5 {{colors.terminal.normal.magenta.hex}}
color6 {{colors.terminal.normal.cyan.hex}}
color7 {{colors.terminal.normal.white.hex}}
color8 {{colors.terminal.bright.black.hex}}
color9 {{colors.terminal.bright.red.hex}}
color10 {{colors.terminal.bright.green.hex}}
color11 {{colors.terminal.bright.yellow.hex}}
color12 {{colors.terminal.bright.blue.hex}}
color13 {{colors.terminal.bright.magenta.hex}}
color14 {{colors.terminal.bright.cyan.hex}}
color15 {{colors.terminal.bright.white.hex}}
background {{colors.terminal.background.hex}}
selection_foreground {{colors.terminal.selection_fg.hex}}
cursor {{colors.terminal.cursor.hex}}
cursor_text_color {{colors.terminal.cursor_text.hex}}
foreground {{colors.terminal.foreground.hex}}
selection_background {{colors.terminal.selection_bg.hex}}
active_border_color {{colors.primary.hex}}
inactive_border_color {{colors.secondary.hex}}

active_tab_foreground   {{colors.on_primary.hex}}
active_tab_background   {{colors.primary.hex}}
inactive_tab_foreground {{colors.on_surface_variant.hex}}
inactive_tab_background {{colors.surface_variant.hex}}
cursor_trail_color      {{colors.on_surface_variant.hex}}
