#font_size 24

# map ctrl+space launch --stdin-source=@screen_scrollback --stdin-add-formatting nvim
# map alt+space launch --type=overlay --stdin-source=@screen_scrollback nvim -Rm

# clear terminal without deleting scrollback
map ctrl+l clear_terminal scroll active

window_padding_width 2 4

include colors.conf
